<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>latest</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_14_18_48_916.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_14_19_17_965.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_14_20_42_224.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_14_21_10_960.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_14_26_03_115.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_14_28_09_682.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_14_28_51_897.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_14_29_33_725.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_14_32_07_261.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_14_33_00_727.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_14_33_13_171.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_14_35_16_233.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_14_35_34_834.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_14_36_34_304.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_14_44_55_154.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_14_47_05_041.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_14_47_47_978.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_14_48_09_110.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_14_48_19_806.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_14_49_19_155.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_14_49_45_756.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_14_50_23_314.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_14_59_28_146.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_15_02_20_793.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_15_02_45_292.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_15_03_01_499.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_15_03_19_478.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_15_03_39_779.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_15_53_33_324.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_16_33_26_989.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_16_41_21_290.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_16_42_08_343.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-28_16_42_51_022.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-31_11_09_17_304.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-31_11_09_59_744.cs" />
    <Compile Include="Pages\Color\.vshistory\Create.cs\2026-03-31_16_19_32_574.cs" />
    <Compile Include="Pages\Color\.vshistory\Delete.cs\2026-03-29_16_09_15_238.cs" />
    <Compile Include="Pages\Color\.vshistory\Delete.cs\2026-03-29_16_09_30_981.cs" />
    <Compile Include="Pages\Color\.vshistory\Delete.cs\2026-03-29_16_09_59_984.cs" />
    <Compile Include="Pages\Color\.vshistory\Delete.cs\2026-03-29_16_10_20_746.cs" />
    <Compile Include="Pages\Color\.vshistory\Delete.cs\2026-03-29_16_10_34_713.cs" />
    <Compile Include="Pages\Color\.vshistory\Delete.cs\2026-03-29_16_14_44_266.cs" />
    <Compile Include="Pages\Color\.vshistory\Delete.cs\2026-03-29_16_16_20_739.cs" />
    <Compile Include="Pages\Color\.vshistory\Delete.cs\2026-03-29_16_17_47_693.cs" />
    <Compile Include="Pages\Color\.vshistory\Delete.cs\2026-03-29_16_17_53_093.cs" />
    <Compile Include="Pages\Color\.vshistory\Delete.cs\2026-03-29_16_17_57_416.cs" />
    <Compile Include="Pages\Color\.vshistory\Delete.cs\2026-03-29_16_18_08_639.cs" />
    <Compile Include="Pages\Color\.vshistory\Delete.cs\2026-03-29_16_36_52_942.cs" />
    <Compile Include="Pages\Color\.vshistory\Delete.cs\2026-03-29_16_40_37_048.cs" />
    <Compile Include="Pages\Color\.vshistory\Edit.cs\2026-03-28_14_18_59_926.cs" />
    <Compile Include="Pages\Color\.vshistory\Edit.cs\2026-03-28_14_19_20_004.cs" />
    <Compile Include="Pages\Color\.vshistory\Edit.cs\2026-03-28_14_31_27_597.cs" />
    <Compile Include="Pages\Color\.vshistory\Edit.cs\2026-03-28_14_52_13_901.cs" />
    <Compile Include="Pages\Color\.vshistory\Edit.cs\2026-03-28_14_52_28_678.cs" />
    <Compile Include="Pages\Color\.vshistory\Edit.cs\2026-03-28_14_53_02_762.cs" />
    <Compile Include="Pages\Color\.vshistory\Edit.cs\2026-03-28_14_53_30_726.cs" />
    <Compile Include="Pages\Color\.vshistory\Edit.cs\2026-03-28_14_54_39_634.cs" />
    <Compile Include="Pages\Color\.vshistory\Edit.cs\2026-03-28_14_56_15_363.cs" />
    <Compile Include="Pages\Color\.vshistory\Edit.cs\2026-03-28_15_03_35_516.cs" />
    <Compile Include="Pages\Color\.vshistory\Edit.cs\2026-03-29_15_42_46_042.cs" />
    <Compile Include="Pages\Color\.vshistory\Edit.cs\2026-03-29_15_52_50_079.cs" />
    <Compile Include="Pages\Color\.vshistory\Edit.cs\2026-03-29_15_53_35_546.cs" />
    <Compile Include="Pages\Color\.vshistory\Edit.cs\2026-03-31_11_26_23_280.cs" />
    <Compile Include="Pages\Color\.vshistory\Edit.cs\2026-03-31_11_26_49_595.cs" />
    <Compile Include="Pages\Color\.vshistory\Edit.cs\2026-03-31_11_27_10_800.cs" />
    <Compile Include="Pages\Color\.vshistory\Edit.cs\2026-03-31_11_27_14_543.cs" />
    <Compile Include="Pages\Color\.vshistory\Edit.cs\2026-03-31_13_57_43_304.cs" />
    <Compile Include="Pages\Color\.vshistory\Edit.cs\2026-03-31_13_57_54_289.cs" />
    <Compile Include="Pages\Color\.vshistory\Edit.cs\2026-03-31_14_01_25_402.cs" />
    <Compile Include="Pages\Color\.vshistory\Edit.cs\2026-03-31_14_08_42_718.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="coverlet.collector" Version="6.0.4" />
    <PackageReference Include="EPPlus" Version="8.4.2" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.14.0" />
    <PackageReference Include="NUnit" Version="4.3.2" />
    <PackageReference Include="NUnit.Analyzers" Version="4.7.0" />
    <PackageReference Include="NUnit3TestAdapter" Version="5.0.0" />
    <PackageReference Include="Selenium.Support" Version="4.41.0" />
    <PackageReference Include="Selenium.WebDriver" Version="4.41.0" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="NUnit.Framework" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ImageTest\" />
  </ItemGroup>

</Project>
